trigger: none
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release 

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: thanks_data
        displayName: 'Generate Thanks Data Stage'
        jobs:  
          - job: ProcessThanksData
            displayName: 'Generate .NET Thanks Data'
            timeoutInMinutes: 1440
            cancelTimeoutInMinutes: 5
            variables:
              HAS_CORE_JSON: 'false'
            steps:
              - checkout: self
                clean: true 
              - task: UseDotNet@2
                displayName: Install .NET 9
                inputs:
                  packageType: 'sdk'
                  version: '9.x'
              - task: PowerShell@2
                displayName: 'Prepare .NET Thanks Data Tool'
                env:
                  GITHUB_CLIENTID: $(github.clientId)
                  GITHUB_CLIENTSECRET: $(github.clientSecret)
                  GITHUB_TOKEN: $(github.oauthToken)
                inputs:
                  targetType: 'inline'
                  script: |
                    $ErrorActionPreference = "Stop"

                    Write-Host "Setting up user secrets..."
                    
                    # Check if user secrets are already initialized
                    try {
                        dotnet user-secrets list | Out-Null
                        Write-Host "User secrets already initialized"
                    }
                    catch {
                        Write-Host "Initializing user secrets..."
                        dotnet user-secrets init
                    }
                    
                    Write-Host "Setting GitHub credentials..."
                    dotnet user-secrets set GITHUB_CLIENTID "$env:GITHUB_CLIENTID"
                    dotnet user-secrets set GITHUB_CLIENTSECRET "$env:GITHUB_CLIENTSECRET"
                    dotnet user-secrets set GITHUB_TOKEN "$env:GITHUB_TOKEN"
                    
                    Write-Host "Current user secrets:"
                    dotnet user-secrets list
                    
                    Write-Host "Restoring and building project..."
                    dotnet restore
                    dotnet build --configuration Release
              - task: PowerShell@2
                displayName: 'Run .NET Thanks Data Tool'
                env:
                  GITHUB_TOKEN: $(github.oauthToken)
                inputs:
                  targetType: 'inline'
                  script: |
                    $ErrorActionPreference = "Stop"
                    
                    Write-Host "Starting .NET Thanks Data Tool..."
                    
                    # Start the process with timeout (24 hours = 86400 seconds)
                    $process = Start-Process -FilePath "dotnet" -ArgumentList "run", "--project", "dotnetthanks-loader.csproj", "--configuration", "Release", "diff" -PassThru -NoNewWindow
                    
                    # Wait for 24 hours (86400000 milliseconds)
                    $finished = $process.WaitForExit(86400000)
                    
                    if (-not $finished) {
                        Write-Host "Process timed out after 24 hours, terminating..."
                        $process.Kill()
                        $process.WaitForExit()
                        throw "Process timed out after 24 hours"
                    }
                    
                    $exitCode = $process.ExitCode
                    Write-Host "Process completed with exit code: $exitCode"
                    
                    if ($exitCode -ne 0) {
                        throw "dotnet run failed with exit code $exitCode"
                    }
                    
                    # Check if core.json was generated
                    if (Test-Path "core.json") {
                        Write-Host "Generated core.json successfully"
                        Write-Host "##vso[task.setvariable variable=HAS_CORE_JSON]true"
                    } else {
                        Write-Host "##vso[task.setvariable variable=HAS_CORE_JSON]false"
                        Write-Host "WARNING: core.json not generated, downstream tasks will be skipped."
                    }