#!/bin/bash
# GitHub REST API script to update dotnet/website repo with new core.json
# Replaces git clone + git push + gh pr create with pure REST API calls
# Usage: ./update-website-thanks-data.sh <GITHUB_TOKEN> <CORE_JSON_PATH> <BUILD_ID>

set -euo pipefail

GITHUB_TOKEN="${GITHUB_TOKEN:?GITHUB_TOKEN is required}"
CORE_JSON_PATH="${1:?CORE_JSON_PATH is required}"
BUILD_ID="${2:?BUILD_ID is required}"

GITHUB_API="https://api.github.com"
REPO_OWNER="dotnet"
REPO_NAME="website"
TARGET_PATH="website-resources/blob-assets/json/thanks/core.json"
BRANCH_NAME="thanks-data-update-${BUILD_ID}"
CURR_MONTH=$(date -u +%B)
CURR_YEAR=$(date -u +%Y)

# Verify source file exists
if [ ! -f "$CORE_JSON_PATH" ]; then
    echo "ERROR: Source file not found: $CORE_JSON_PATH"
    exit 1
fi

echo "Starting GitHub REST API update process..."
echo "Target: $REPO_OWNER/$REPO_NAME"
echo "Branch: $BRANCH_NAME"
echo "File: $TARGET_PATH"

# Step 1: Get current file SHA from main branch (needed for update)
echo "Step 1: Fetching current file SHA from main branch..."
CURRENT_SHA=$(curl -s \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "$GITHUB_API/repos/$REPO_OWNER/$REPO_NAME/contents/$TARGET_PATH?ref=main" \
  | jq -r '.sha // empty')

if [ -z "$CURRENT_SHA" ]; then
    echo "INFO: File does not exist in main branch, will create new file"
    CURRENT_SHA=""
else
    echo "Current file SHA: $CURRENT_SHA"
fi

# Step 2: Encode new core.json content in base64
echo "Step 2: Preparing new file content..."
NEW_CONTENT=$(base64 -w 0 < "$CORE_JSON_PATH")
echo "File size: $(wc -c < "$CORE_JSON_PATH") bytes"

# Step 2b: Get main branch HEAD SHA
echo "Step 2b: Getting main branch HEAD SHA..."
MAIN_SHA=$(curl -s \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "$GITHUB_API/repos/$REPO_OWNER/$REPO_NAME/git/refs/head/main" \
  | jq -r '.object.sha // empty')

if [ -z "$MAIN_SHA" ]; then
    echo "ERROR: Could not get main branch SHA"
    exit 1
fi

# Step 2c: Create the new branch
echo "Step 2c: Creating branch $BRANCH_NAME from main..."
CREATE_BRANCH_RESPONSE=$(curl -s -w "\n%{http_code}" \
  -X POST \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "{\"ref\": \"refs/heads/$BRANCH_NAME\", \"sha\": \"$MAIN_SHA\"}" \
  "$GITHUB_API/repos/$REPO_OWNER/$REPO_NAME/git/refs")

HTTP_CODE=$(echo "$CREATE_BRANCH_RESPONSE" | tail -n1)
if [ "$HTTP_CODE" == "422" ]; then
    echo "WARNING: Branch already exists, proceeding..."
elif [ "$HTTP_CODE" == "201" ]; then
    echo "Branch created (HTTP $HTTP_CODE)"
else
    echo "ERROR: Failed to create branch (HTTP $HTTP_CODE)"
    echo "$CREATE_BRANCH_RESPONSE" | head -n-1
    exit 1
fi
echo "Branch created (HTTP $HTTP_CODE)"


# Step 3: Update/Create file via Contents API
echo "Step 3: Updating file via GitHub Contents API..."
COMMIT_MESSAGE="Update .NET thanks data - $CURR_MONTH $CURR_YEAR"

UPDATE_PAYLOAD=$(jq -n \
  --arg message "$COMMIT_MESSAGE" \
  --arg content "$NEW_CONTENT" \
  --arg branch "$BRANCH_NAME" \
  --arg sha "$CURRENT_SHA" \
  'if $sha != "" then {message: $message, content: $content, branch: $branch, sha: $sha}
   else {message: $message, content: $content, branch: $branch} end')

UPDATE_RESPONSE=$(curl -s -w "\n%{http_code}" \
  -X PUT \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "$UPDATE_PAYLOAD" \
  "$GITHUB_API/repos/$REPO_OWNER/$REPO_NAME/contents/$TARGET_PATH")

HTTP_CODE=$(echo "$UPDATE_RESPONSE" | tail -n1)
RESPONSE_BODY=$(echo "$UPDATE_RESPONSE" | head -n-1)

if [ "$HTTP_CODE" != "200" ] && [ "$HTTP_CODE" != "201" ]; then
    echo "ERROR: Failed to update file (HTTP $HTTP_CODE)"
    echo "$RESPONSE_BODY"
    exit 1
fi

echo "File updated successfully (HTTP $HTTP_CODE)"

# Step 4: Create PR via Pull Requests API
echo "Step 4: Creating pull request via GitHub Pull Requests API..."

PR_TITLE="Update .NET thanks data - $CURR_MONTH $CURR_YEAR"
PR_BODY="**Automated .NET Thanks Data Update**

Build ID: $BUILD_ID

This PR updates the core.json file with the latest contributor acknowledgments.

---
*This PR was automatically generated by the dotnet-website-thanks-data-automation pipeline.*"

PR_PAYLOAD=$(jq -n \
  --arg title "$PR_TITLE" \
  --arg head "$BRANCH_NAME" \
  --arg body "$PR_BODY" \
  '{title: $title, head: $head, base: "main", body: $body}')

PR_RESPONSE=$(curl -s -w "\n%{http_code}" \
  -X POST \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "$PR_PAYLOAD" \
  "$GITHUB_API/repos/$REPO_OWNER/$REPO_NAME/pulls")

HTTP_CODE=$(echo "$PR_RESPONSE" | tail -n1)
RESPONSE_BODY=$(echo "$PR_RESPONSE" | head -n-1)

if [ "$HTTP_CODE" != "201" ]; then
    echo "ERROR: Failed to create PR (HTTP $HTTP_CODE)"
    echo "$RESPONSE_BODY"
    exit 1
fi

PR_NUMBER=$(echo "$RESPONSE_BODY" | jq -r '.number')
PR_URL=$(echo "$RESPONSE_BODY" | jq -r '.html_url')

echo "Pull request created successfully!"
echo "PR #$PR_NUMBER: $PR_URL"
echo "##vso[task.setvariable variable=PR_NUMBER]$PR_NUMBER"
echo "##vso[task.setvariable variable=PR_URL]$PR_URL"

echo "SUCCESS: All REST API operations completed"
